languages = {
    'en': 'English',
    'vi': 'Tiếng Việt',
    'fi': 'Suomi',
    'sv': 'Svenska'
}

text = {
    'en': {
        'select_experiment': 'Select Experiment',
        'select_country': 'Select Country',
        'enhanced_dC_loss': 'Enhanced ΔC_loss Visualization for',
        'no_data': 'No data available for the selected country and experiment.',
        'carbon_budget': 'Enhanced Carbon Budget for',
        'select_year': 'Select Year',
        'gpt_analysis': 'GPT Analysis for',
        'ask_question': 'Ask a question about the data or chart:',
        'processing': 'Processing your question...',
        'analysis_result': 'Analysis Result',
        'error': 'An error occurred:',
        'suggested_questions': 'Suggested Follow-up Questions',
        'year': 'Year',
        'dC_loss_label': 'ΔC_loss (TgCO₂)',
        'co2_emissions': 'CO₂ Emissions (TgCO₂)',
        'component': 'Component',
        'value': 'Value',
        'carbon_budget_title': 'Carbon Budget for {country_name} in {year}',
        'select_language': 'Select Language',
        'select_dataset': 'Select Dataset',
        'dataset_not_available': 'This dataset is not available yet.',
        'CO2_Budget_countries': 'CO2 Budget Countries',
        'learn_more': 'Learn more',
        'explore_co2': 'Explore carbon dioxide levels over the last 50 years',
        'methane_impact': 'How does methane impact global warming compared to CO²?',
        'explore_data': 'Would you like to explore data on CO² emissions or methane today?',
        'fetch_data': 'Fetch Data'
    },
    'vi': {
        'select_experiment': 'Chọn Thí nghiệm',
        'select_country': 'Chọn Quốc gia',
        'enhanced_dC_loss': 'Hình ảnh hóa ΔC_loss nâng cao cho',
        'no_data': 'Không có dữ liệu cho quốc gia và thí nghiệm đã chọn.',
        'carbon_budget': 'Ngân sách Carbon nâng cao cho',
        'select_year': 'Chọn Năm',
        'gpt_analysis': 'Phân tích GPT cho',
        'ask_question': 'Đặt câu hỏi về dữ liệu hoặc biểu đồ:',
        'processing': 'Đang xử lý câu hỏi của bạn...',
        'analysis_result': 'Kết quả Phân tích',
        'error': 'Đã xảy ra lỗi:',
        'suggested_questions': 'Câu hỏi tiếp theo gợi ý',
        'year': 'Năm',
        'dC_loss_label': 'ΔC_loss (TgCO₂)',
        'co2_emissions': 'Lượng phát thải CO₂ (TgCO₂)',
        'component': 'Thành phần',
        'value': 'Giá trị',
        'carbon_budget_title': 'Ngân sách Carbon cho {country_name} năm {year}',
        'select_language': 'Chọn Ngôn ngữ',
        'select_dataset': 'Chọn Bộ Dữ Liệu',
        'dataset_not_available': 'Bộ dữ liệu này chưa có sẵn.',
        'CO2_Budget_countries': 'Ngân sách CO2 các Quốc gia',
        'learn_more': 'Tìm hiểu thêm',
        'explore_co2': 'Khám phá mức độ carbon dioxide trong 50 năm qua',
        'methane_impact': 'Khí metan ảnh hưởng đến sự nóng lên toàn cầu so với CO² như thế nào?',
        'explore_data': 'Bạn có muốn khám phá dữ liệu về phát thải CO² hoặc metan hôm nay không?',
        'fetch_data': 'Lấy dữ liệu'
    },
    'fi': {
        'select_experiment': 'Valitse koe',
        'select_country': 'Valitse maa',
        'enhanced_dC_loss': 'Parannettu ΔC_loss-visualisointi maalle',
        'no_data': 'Valitulle maalle ja kokeelle ei ole tietoja.',
        'carbon_budget': 'Parannettu hiilibudjetti maalle',
        'select_year': 'Valitse vuosi',
        'gpt_analysis': 'GPT-analyysi maalle',
        'ask_question': 'Kysy kysymys datasta tai kaaviosta:',
        'processing': 'Käsitellään kysymystäsi...',
        'analysis_result': 'Analyysin tulos',
        'error': 'Tapahtui virhe:',
        'suggested_questions': 'Ehdotetut jatkokysymykset',
        'year': 'Vuosi',
        'dC_loss_label': 'ΔC_loss (TgCO₂)',
        'co2_emissions': 'CO₂-päästöt (TgCO₂)',
        'component': 'Komponentti',
        'value': 'Arvo',
        'carbon_budget_title': 'Hiilibudjetti maalle {country_name} vuonna {year}',
        'select_language': 'Valitse kieli',
        'select_dataset': 'Valitse tietojoukko',
        'dataset_not_available': 'Tämä tietojoukko ei ole vielä saatavilla.',
        'CO2_Budget_countries': 'CO2-budjetti maittain',
        'learn_more': 'Lue lisää',
        'explore_co2': 'Tutki hiilidioksiditasoja viimeisten 50 vuoden ajalta',
        'methane_impact': 'Miten metaani vaikuttaa ilmaston lämpenemiseen verrattuna CO²:een?',
        'explore_data': 'Haluatko tutkia tietoja CO²-päästöistä tai metaanista tänään?',
        'fetch_data': 'Hae tiedot'
    },
    'sv': {
        'select_experiment': 'Välj experiment',
        'select_country': 'Välj land',
        'enhanced_dC_loss': 'Förbättrad ΔC_loss-visualisering för',
        'no_data': 'Ingen data tillgänglig för valt land och experiment.',
        'carbon_budget': 'Förbättrad koldioxidbudget för',
        'select_year': 'Välj år',
        'gpt_analysis': 'GPT-analys för',
        'ask_question': 'Ställ en fråga om data eller diagram:',
        'processing': 'Bearbetar din fråga...',
        'analysis_result': 'Analysresultat',
        'error': 'Ett fel uppstod:',
        'suggested_questions': 'Föreslagna följdfrågor',
        'year': 'År',
        'dC_loss_label': 'ΔC_loss (TgCO₂)',
        'co2_emissions': 'CO₂-utsläpp (TgCO₂)',
        'component': 'Komponent',
        'value': 'Värde',
        'carbon_budget_title': 'Koldioxidbudget för {country_name} år {year}',
        'select_language': 'Välj språk',
        'select_dataset': 'Välj dataset',
        'dataset_not_available': 'Detta dataset är inte tillgängligt ännu.',
        'CO2_Budget_countries': 'CO2-budget per land',
        'learn_more': 'Läs mer',
        'explore_co2': 'Utforska koldioxidnivåer under de senaste 50 åren',
        'methane_impact': 'Hur påverkar metan den globala uppvärmningen jämfört med CO²?',
        'explore_data': 'Vill du utforska data om CO²-utsläpp eller metan idag?',
        'fetch_data': 'Hämta data'
    }
}

# Mapping language codes to language names for GPT prompt
language_names = {
    'en': 'English',
    'vi': 'Vietnamese',
    'fi': 'Finnish',
    'sv': 'Swedish'
}

def get_language_display_name(lang_code, current_lang_code):
    return languages[lang_code]